---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helloworld-tf
spec:
  interval: 30s
  url: https://github.com/javierm2k9/tf-controller-helloworld
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: helloworld-v2
spec:
  path: ./terraform
  approvePlan: auto
  destroyResourcesOnDeletion: true
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: helloworld-v2
  writeOutputsToSecret:
    name: helloworld-outputs
