apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-v2
  namespace: argocd
spec:
  destination:
    namespace: dev2
    server: 'https://kubernetes.default.svc'
  source:
    path: ./infra
    repoURL: 'https://github.com/javierm2k9/tf-controller-helloworld'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - AutoCreateFluxResources=true
      - FluxSubsystem=true